spring.application.name=aad_final_project
spring.datasource.url=jdbc:mysql://localhost:3306/aadfinalproject?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
